### ISSUE TITLE
Karma throws exception

### ISSUE THREAD

**Issue by zazoomauro** [NagRock/ts-mockito#1]
Karma throws this exception launching tests with ts-mockito:

`Error: XHR error (404 Not Found) loading http://localhost:9876/ts-mockito`

**Comment by NagRock** [comment]
Can you share some more details? How you import ts-mockito into your project?

**Comment by zazoomauro** [comment]
I'm installing with with npm `npm install ts-mockito --save-dev`
then
`
import {it, describe, expect} from "angular2/testing";
import {HardService} from "./HardService";
import {EasyService} from "./EasyService";
import {mock} from "ts-mockito";

describe('Hard Service Tests', () => {
    let mockEasyService: EasyService = mock(EasyService);
    let hardService: HardService = new HardService(mockEasyService);

    it('getRandomLengthDogName should return the dog length number', () => {
        // Arrange.
        var dogName = 'foo bar';


        // Act.
        var length = hardService.getRandomLengthDogName();

        // Assert.
        expect(length).toEqual(dogName.length);
    });
});
`

**Comment by NagRock** [comment]
Hmmm I'm using webpack. Can you give me a link to your project with sample app using systemjs?

**Comment by zazoomauro** [comment]
@NagRock is not public so I cannot share any url. BTW I'm using a classic angular2 installation

**Comment by NagRock** [comment]
Ok so I will try it but it will be faster if you will put a new project on github.

**Comment by zazoomauro** [comment]
how are u loading ts-mockito?

**Comment by NagRock** [comment]
I've forked angular quickstart and added ts-mockito to it:

[quickstart-fork](https://github.com/NagRock/quickstart)

You can clone it and run:
`npm run install`
`npm run test-once`

And remember to get instance of mocked object before using it:

`let mockEasyService: EasyService = mock(EasyService);
let hardService: HardService = new HardService(instance(mockEasyService)); // instance(mockEasyService)`

And look at my commit to see what need to be added in quickstart to run ts-mockito with systemjs
[commits](https://github.com/NagRock/quickstart/commits/master)

**Comment by zazoomauro** [comment]
@NagRock Thanks
