### ISSUE TITLE
Why the `reset` function doesn't reset the mock configuration?

### ISSUE THREAD

**Issue by michalstocki** [NagRock/ts-mockito#10]
When I can see the `reset` function, I expect them to reset not only the calls which were recorded, but also the mocked functionality of all the methods.

I expect the following test to pass:
```typescript
describe('Mock resetting', () => {
    it('should reset a value configured to be returned', () => {
        // given
        const myClassMock = mock(MyClass);
        when(myClassMock.methodB('some string')).thenReturn('other string');
        const myClass = instance(myClassMock);
        reset(myClassMock);

        // when
        const result = myClass.methodB('some string');

        // then
        expect(result).to.not.equal('other string');
    });
});

class MyClass {

    public methodB(someArgument:string):string {
        return `provided value: ${someArgument}`;
    }
}
```

Here is a link for the test within the configured project:
https://github.com/michalstocki/ts-mockito-example/blob/master/test/spec/extension/resetting/mock-resetting.spec.ts

**Comment by NagRock** [comment]
Fixed in v1.1.4 https://github.com/NagRock/ts-mockito/releases/tag/v1.1.4
