### ISSUE TITLE
when not behaving as expected

### ISSUE THREAD

**Issue by kevupton** [NagRock/ts-mockito#100]
I seem to be having some trouble with getting my testing to work.
This is most likely an error on my part as I am new to ts-mockito.

However I am attempting to mock some services.

I am attempting to get my method `getCampaigns()` to throw an error however it doesnt seem to do anything no matter what I seem to do.

```js
  let mockCampaignApiFactory: CampaignApiFactory;
  let mockUserService: UserService;
  let mockCampaignApi: CampaignApi;

  beforeEach(async(() => {
    mockCampaignApiFactory = mock(CampaignApiFactory);
    mockCampaignApi = mock(CampaignApi);
    mockUserService = mock(UserService);

    when(mockCampaignApiFactory.getInstance()).thenReturn(mockCampaignApi);
    when(mockCampaignApi.getCampaigns(anything())).thenThrow(new Error('rip'));

    console.log(mockCampaignApi.getCampaigns(null)); 
```

The console log just logs a `MethodToStub` object.

When I do this:
```js
    // when(mockCampaignApiFactory.getInstance()).thenReturn({
    //   getCampaigns() {
    //     return Observable.of([]);
    //   }
    // } as any);
    // when(mockCampaignApi.getCampaigns(anything())).thenThrow(new Error('rip'));
```
If i attempt to change `thenThrow` to something like `thenReturn(false)` it will still return the same object. 
Im not sure why the `thenReturn` and `thenThrow` values are not being fired or calling. 

Is there somethign stupid that I am not doing. The first example seems to work and the only difference is the argument. 
(`getInstance()` returns the value that I give it.) but the `mockCampaignApi` does not return or behave at all how i tell it.

**Comment by chrisdevereux** [comment]
Had the exact same issue getting started. It's easy to miss in the docs, but you need to use `instance()` to get the mock instance to call stubbed methods on.

Example from the readme:

```
// Creating mock
let mockedFoo:Foo = mock(Foo);

// stub method before execution
when(mockedFoo.getBar(3)).thenReturn('three');

// Getting instance
let foo:Foo = instance(mockedFoo);

// prints three
console.log(foo.getBar(3));
```

**Comment by kevupton** [comment]
omg this was exactly it. haha. It is really too easy to miss. It would be good if there was some better error message for this situation.

**Comment by NagRock** [comment]
Hi @kevupton, unfortunately as mentioned here: https://github.com/NagRock/ts-mockito/issues/90

This is currently impossible without some breaking changes.
