### ISSUE TITLE
@types/lodash should be a dev dependency or a peer dependency

### ISSUE THREAD

**Issue by tiberiucorbu** [NagRock/ts-mockito#11]
Hey! First of all I want to thank you for the awesome Mocking Frameworks that you made.

In package.json `@types/lodash` is referenced as a direct dependency and its loaded automatically in the `ts-mockito` depended projects. 

It wouldn't be a problem if everyone would use `lodash` but that's not the case. At the compile the variable `_` enters in conflict with other libraries that define the same variable name.

Resulting in a nasty, not so easy to debug :

> Error "Duplicate identifier '_'"

As the users of this framework use only the compiled .js with the typing definitions the @types/lodash is not required into dependencies.

**Comment by NagRock** [comment]
Thx, for reporting this. I will check it and fix it soon.

**Comment by NagRock** [comment]
Should be fixed in https://github.com/NagRock/ts-mockito/releases/tag/v1.1.5
