### ISSUE TITLE
Please provide an example on how to mock an interface

### ISSUE THREAD

**Issue by jeffsaremi** [NagRock/ts-mockito#114]
I'm trying to do that using something like this:

`const mockGlContext: GlContext = mock(GlContext);`

but i get:

> Cannot invoke an expression whose type lacks a call signature. Type '{ spy: <T>(instanceToSpy: T) => T; mock: <T>(clazz: (new (...args: any[]) => T) | (Function & { p...' has no compatible call signatures.

**Comment by jeffsaremi** [comment]
Actually i just went and replaced the interface with an abstract implementation of it and I stil get this:

`Cannot invoke an expression whose type lacks a call signature. Type '{ spy: <T>(instanceToSpy: T) => T; mock: <T>(clazz: (new (...args: any[]) => T) | (Function & { p...' has no compatible call signatures.`

There's something wrong with this library
I am using this version:
`    "ts-mockito": "^2.3.0",`

**Comment by cornr** [comment]
What we do to mock interfaces...
For an interface `MyInterface ` create a class `MyInterfaceMock` and let it implement the Interface `MyInterface` and auto generate implementations. The implementations can all just return `undefined`.
In the test case create a mock from `MyInterfaceMock`.

**Comment by jeffsaremi** [comment]
thanks a lot

**Comment by sizilium** [comment]
@cornr isn't this something a mocking framework should do for you automatically? `MyInterface` IS already a mock, a handwritten one. 
I hope ts-mockito will support creating mocks from interface in future. Your solution is fine as a workaround though.

**Comment by cornr** [comment]
@sizilium sure that would be nice. My solution is just a workaround 😄

**Comment by NagRock** [comment]
Version 2.4.0 supports interfaces. https://github.com/NagRock/ts-mockito/releases/tag/v2.4.0

**Comment by cornr** [comment]
awesome. thanks @NagRock
