### ISSUE TITLE
verify async method called from non-async method

### ISSUE THREAD

**Issue by texdc** [NagRock/ts-mockito#116]
I've mocked a dependency which has an `async` method and wish to verify that it is called from a protected method on the test subject.  I've tried setting the test up various ways, but `verify` hasn't been picking up the call, even though I've verified it manually using the debugger in my IDE.

Subject under test:
```ts
    public stuff(): void {
        // ...
        this.foo('test')
    }

    protected async foo(thing: string): Promise<void> {
        if (this.bar !== undefined) {
            return this.bar.do(thing)
        }
    }
```

Test:
```ts
        beforeEach(() => {
            bar = mock(Bar)
            subject = new Subject(instance(bar))
        })

        it('does things', () => {
            const thing: string = 'test'
            when(bar.do(thing)).thenResolve();

            subject.stuff()
            verify(bar.do(thing)).once()
        })
```

Result:
```
Error: Expected "do(strictEqual(test))" to be called at least 1 time(s). But has been called 0 time(s).
```

**Comment by texdc** [comment]
I've resolved it.  I needed to use `anything()` as the strict equal was failing.

**Comment by mmarchois** [comment]
How do you use `anything` ?

**Comment by JamieCorkhill** [comment]
@texdc If you use `anything()`, how can you be sure that the function was called with the expected arguments - or should `capture` be used for that.

Can you provide any advice @NagRock ? And thanks for the great tool.
