### ISSUE TITLE
How to mock an interface

### ISSUE THREAD

**Issue by DonJayamanne** [NagRock/ts-mockito#117]
How do we create a mock of an interface?
Currently this can be done in [typemoq](https://github.com/florinn/typemoq) as follows:
```typescript
// Using an interface as type parameter
const mock: TypeMoq.IMock<IBar> = TypeMoq.Mock.ofType<IBar>();
```

FYI - Creating mock implementations for each interface isn't an option.

**Comment by NagRock** [comment]
This feature is still not implemented.

**Comment by vandammeb** [comment]
@NagRock is there any timeline on this?

**Comment by FibreFoX** [comment]
Looks like this is already available via pull-request: https://github.com/NagRock/ts-mockito/pull/76

@NagRock maybe you could look into that PR and write down what is missing?!

**Comment by pbadenski** [comment]
ETA on this? this a true pain point in an otherwise great library! :D

**Comment by jeep87c** [comment]
Any ETA/update on this? This is such a pain point...

**Comment by NagRock** [comment]
There is problem that it needs to break `getter` / `setter` mocking API. No ETA at the moment

**Comment by jasperblues** [comment]
I can't use this library without this feature.

**Comment by DonJayamanne** [comment]
> I can't use this library without this feature.

I use this library along with `typemoq`. Sucks to use two, but there are benefits of both.

**Comment by dice14u** [comment]
Why would this not work ?
```
const mockIbar = mock(<IBar>{});
const mockFunctionImpl = mock(someFunction);
when(mockIbar.someMethod).doReturn(instance(mockFunctionImpl));
const mockIbarInstance = instance(mockIbar);
```

**Comment by Styrna** [comment]
This is needed !!!

**Comment by jasperblues** [comment]
Still looking forward to this feature. Happy if it is a breaking change. Have some time upcoming to contribute if needed.

**Comment by appsolutegeek** [comment]
me too!, i hit a road block when I noticed I can't mock interfaces. THere is a pull request, is it still being actively checked ?

**Comment by FrancescoBorzi** [comment]
it would be nice indeed to have such a feature

**Comment by IvanGuardado** [comment]
Really important feature. Is someone working on this? I could help...

**Comment by NagRock** [comment]
New version with support for interfaces released: https://github.com/NagRock/ts-mockito/releases/tag/v2.4.0

If something will work not as expected, please create new issue.

**Comment by DonJayamanne** [comment]
@NagRock thanks for adding this feature. Apologies for not noticing this earlier. We've started using this.
