### ISSUE TITLE
Error while stubbing a method to return list

### ISSUE THREAD

**Issue by ashishmahi** [NagRock/ts-mockito#119]
I'm trying to mock a class called `Sample` which has method called `getSomething` which is supposed to return an array . So i mocked this getSomething saying 
let a = [];
`when(sample.getSomething()).theReturns(a)` and then i'm doing some `filter` on getSomething 
but doing that throwing error saying `sample.getSomething().filter` is not a function .
What could be possible reason ?

**Comment by NagRock** [comment]
Hi @ashishmahi probably you forgot about `instance` function. Please look at basic usage: https://github.com/NagRock/ts-mockito#basics

**Comment by ashishmahi** [comment]
i tried with instance now it is `
let a = [];
when(sample.getSomething()).thenReturn(a);`
and error is `Cannot read property 'methodStubCollection' of null`

**Comment by NagRock** [comment]
You should use `mock` for setting behaviors and verify. And pass instance to real code.

And if you want to mock someting on real existing object you should use `spy` instead of `mock`

**Comment by ashishmahi** [comment]
Hey Maciej,
how can we mock setter as we have way to mock getter ?
Thanks in advance
