### ISSUE TITLE
Stub method to return nth argument

### ISSUE THREAD

**Issue by mbyrne00** [NagRock/ts-mockito#130]
I see in #16 and #19 there was work done to capture arguments which is great for verification, however I'd like to set my mock to always return the nth argument. 

This is useful for repository style functions that save an entity and return it again. 

In Java mockito this was achieved with `thenAnswer()`
```
    // Expect specified method call to return the nth argument
    public static <T> void returnArgument(T methodCall, int argumentIndex) {
        when(methodCall).thenAnswer(invocation -> invocation.getArguments()[argumentIndex]);
    }
```

The beauty of this in the TS stack is we can also mimick behaviour of returning a new object with additional fields if required, via spread. If there is a simple workaround in the mean time or if I've missed something then I'd love to hear it. 

Thanks for the great lib!

**Comment by NagRock** [comment]
If I understand your question correctly: `thenCall` should be solution for you.

```typescript
when(mockedFoo.sampleFunction(anything())).thenCall((...args) => {
  console.log(args[0]);
});
```

So you can just get all arguments by `...args`. Or just give them names.

**Comment by mbyrne00** [comment]
Hi - that's exactly what I was after. I don't know how I missed that! Many thanks.
