### ISSUE TITLE
Unable to mock 'toString()'

### ISSUE THREAD

**Issue by Kalagon** [NagRock/ts-mockito#132]
Hey, this might be related to #73.
I am unable to create a mock that responds to calls of 'toString()'.
Setup is as follows:
A base class _Type_
```typescript
export abstract class Type {
    public name: string

    public toString(): string {
        return this.name
    }

    public abstract toTypeCodeString(): string
}
```

A derived class _BasicType_
```typescript
export class BasicType extends Type {
    constructor(name: "void" | "bool" | "float" | "double" | "null" | "int8" | "uint8" | "int16" | "uint16" | "int32" | "uint32" | "int64" | "uint64" | "rune" | "any" | "string" | "int" | "uint" | "byte" | "char") {
        super()
        this.name = name
    }

    public toTypeCodeString(): string {
        return this.name
    }
}
```

And a test for a class that uses _Type_:
```typescript
describe('filled FunctionType', () => {
    let instance: FunctionType

    before(() => {
        let returnType: Type = m.mock(BasicType)
        m.when(returnType.toString()).thenReturn('void')
        instance = new FunctionType()

        instance.returnType = m.instance(returnType)
    })

    it('toString() ', () => {
        expect(instance.toString()).to.equal("() => void")
    })
})
```

Where _FunctionType_ is a class that stores a _Type_ in its _returnType_ member and calls `this.returnType.toString()` inside its own _toString()_.

When running the test I get the following error:
```
  1) filled FunctionType
       "before all" hook:
     TypeError: _this.methodToStub.methodStubCollection.add is not a function
      at /home/oskar/Documents/Work/fyr/node_modules/ts-mockito/lib/MethodStubSetter.js:20:53
      at Array.forEach (<anonymous>)
      at MethodStubSetter.thenReturn (node_modules/ts-mockito/lib/MethodStubSetter.js:19:14)
      at Context.before (test/tests/types/tests/FunctionType.spec.js:22:39)
```

Things I've tried that do not work:
- defining _toString()_ in _BasicType_
- using `m.mock(Type)` instead of `m.mock(BasicType)`

Replacing all occurences of _toString()_ in the test with _toTypeCodeString()_ works as expected.
_FunctionType.toTypeCodeString()_ behaves analogous to _toString()_, using the _toTypeCodeString()_ of its _returnType_ member.

**Comment by NagRock** [comment]
What is `instance = new FunctionType()` in your example?

**Comment by Kalagon** [comment]
It creates the object of the class that I run the tests on. This is what uses the mocked object internally.
_FunctionType_ is a subtype of _Type_ and implements its own _toString()_ like this:
```typescript
public toString(): string {
    ...
    if (this.returnType){
        name += ") => " + this.returnType.toString()
        ...
    return name
}
```

**Comment by NagRock** [comment]
So it looks like, this is related to https://github.com/NagRock/ts-mockito/issues/73
`ts-mockito` uses `toString` to get code of object to find all possible function names. No solution right now.

**Comment by Kalagon** [comment]
Okay, thank you for investigating this. I'll continue to work around it.

**Comment by NagRock** [comment]
I'm closing it as it is same issue as #73
