### ISSUE TITLE
Unable to mock "instanceof ClassXYZ"

### ISSUE THREAD

**Issue by jackdamiels** [NagRock/ts-mockito#133]
I'm failing to mock cases when instanceof operator is used.

e.g. 

method that I am trying to test:

`
   checkIfInstanceOfClassB(candidate: ClassB): boolean {
    return candidate instanceof ClassB
  }
` 

excerpt from test file:
```
const mockedClassB = mock(ClassB);
const instanceOfClassB = instance(mockedClassB)

// this part always fails
expect(verify(checkIfInstanceOfClassB(instanceOfClassB))).toBeTruthy()
```

My question, is there some way to mock this  particular use case?

Thank you in advanced

**Comment by NagRock** [comment]
Hi @jackdamiels. `Mock` and `instance` got different type than `class` that is mocked and can't be checked via `instanceof`.
