### ISSUE TITLE
Getting TypeError: methodStub.hasMatchingInAnyGroup is not a function when trying to mock a WebSocket class

### ISSUE THREAD

**Issue by shaiksyedali** [NagRock/ts-mockito#136]
I am using ws npm module for making websocket client and server connections.

In my Unit Tests, i am trying to mock the WebSocket class using ts-mockito.

```
import * as WebSocket from 'ws';

describe('Stream Resource Test', () => {

  it('Happy Path Test', async () => {
    const streamResource = new StreamResource();

    const mockSocket = mock(WebSocket);

    const response = await streamResource.createStream(mockSocket);

    expect(response).not.equal(null);
    expect(response.streamState).equal('Active');

  });
});
```

I am getting **TypeError: methodStub.hasMatchingInAnyGroup** is not a function now.

Any pointers?

**Comment by dice14u** [comment]
you need to instance your mock so `await streamResource.createStream(instance(mockSocket));`

**Comment by NagRock** [comment]
@shaiksyedali did @dice14u proposition helped you?
