### ISSUE TITLE
Release 2.4.1 is tagged as 2.4.2

### ISSUE THREAD

**Issue by jensbodal** [NagRock/ts-mockito#154]
Not sure if this was released by mistake, but there's no release information in https://github.com/NagRock/ts-mockito/releases and [`package.json`](https://github.com/NagRock/ts-mockito/commit/75ef19e592019e54c20575aae7bf62f381141174) update shows `2.4.1`

**Comment by NagRock** [comment]
`2.4.1` has been released but with bug that has been fixed within a one day. So it is missing on releases page. But probably I've forgotten about tag. Thanks for catching this

**Comment by jensbodal** [comment]
Thanks, but the point was the version in the package.json doesn't match the version it is tagged as. Ideally 2.4.3 is simply released with the version in the package.json matching the version it is tagged as.
