### ISSUE TITLE
Are PRs currently being considered?

### ISSUE THREAD

**Issue by mixedCase** [NagRock/ts-mockito#160]
I noticed there have been a few PRs open for a long time, one of them at least which would've saved me quite a bit of time while debugging due to the `any` typing of `deepEqual` creating poor error messages on a type mismatch.

I just wanted to know if these PRs are being considered for inclusion or if it's more of a personal/company project and community contribution should be done on a fork? Sorry if I come across as entitled to your time (to state the obvious: I am not) due to the nature of the question, I saw no contribution guidelines and genuinely want to know if it's something that is simply not in scope.

Regardless, thank you for your work on ts-mockito!

**Comment by NagRock** [comment]
Hi, yes some PR are open for a long time. I try to merge PR's in a free time but also I got to think to not break API and not block things for future so trying to merge just the most important one. And also I do not have too much free time but will try to take a look at all of them.

`deepEqual` type checking released in https://github.com/NagRock/ts-mockito/releases/tag/v2.5.0
