### ISSUE TITLE
Mock of async/await method doesn't work ?

### ISSUE THREAD

**Issue by mmarchois** [NagRock/ts-mockito#171]
When I try to mock a class with an async/await method, it will trow `TypeError: canRegisterSpecification.isSatisfiedBy is not a function`

```
class CanRegisterSpecification implements ISpecification {
    public isSatisfiedBy = async (email: string): Promise<boolean> => {/*...*/}
}

const canRegisterSpecification = mock(CanRegisterSpecification);
when(canRegisterSpecification.isSatisfiedBy(email)).thenResolve(false);
```

**Comment by lordrip** [comment]
Bear in mind that `isSatisfiedBy` is not a method of the class, is a property that holds a function, therefore the value is bull (not function :)) then, I'll suggest to either change the signature from property to a class method or maybe mock the getter like this:

```
when(canRegisterSpecification.isSatisfiedBy).thenReturn(() => new Promise.resolve(false))
```

**Comment by mmarchois** [comment]
@lordrip Thank you for your answer. I didn't understand correctly. `isSatisfiedBy` is not interpreted as a method but as a property? How to transform it as a class method ?

**Comment by lordrip** [comment]
```
class CanRegisterSpecification implements ISpecification {
    // This is a property, notice the equal sign for assignment
    public isSatisfiedBy = async (email: string): Promise<boolean> => {/*...*/}

    // We can omit public keyword since is the default, and also add async since we're returning a promise
    async isSatisfyMethod(email: string): Promise<boolean> {
         /*...*/
    }
}
```
