### ISSUE TITLE
Import functions other than mock, when, verify and instance

### ISSUE THREAD

**Issue by Jnforja** [NagRock/ts-mockito#2]
How should i import functions other than mock, when, verify and instance ?
Since in the main file (lib/ts-mockito.js) only those 4 functions are exported how should import other functions like anything ?  This without specifying the path to the specific file where the function is exported.

**Comment by NagRock** [comment]
IDE should import `anything` and other methods automatically. But you are right and it would be easier to import all functions from main file. I will fix it soon.

**Comment by michalstocki** [comment]
Yes, it could be nice to have all exported functions described also in a single `.d.ts` file. Then it could be used as na API documentation. For example: there is no place in the README, where the all available matchers are described, so it's hard to guess what are possible matching options.

**Comment by NagRock** [comment]
In version 1.0.0-beta.0 I've moved all functions to main file `ts-mockito` so now you can import all of it from one place. Not that all previously added import got to be changed.
