### ISSUE TITLE
multiple instances of mocked objects

### ISSUE THREAD

**Issue by bjverhoe** [NagRock/ts-mockito#20]
Hi,
When I was trying out `ts-mockito` I noticed that the `instance()` method does not create different instances of the mocked Class. 

For example I have a class `User` with a field `id`. When creating two mocked objects:
```
let mockedUser = mock(User);
let user1 = instance(mockedUser);
let user2 = instance(mockedUser);
if(user1.id === user2.id)
  return true;
else return false;
```
This code yields true. Am I using the instance method in the wrong way?

**Comment by michalstocki** [comment]
`instance()` is a kind of getter for the instance object corresponding with the provided mock object. If you would like to get two mocks of the same class, just call `mock()` twice.

**Comment by NagRock** [comment]
Hi @bjverhoe, as @michalstocki mentioned `instance()` method gets instance from specific mock. Because all behaviors are defined by mock, you should get one instance per one mock.

```
let mockedUser1 = mock(User);
let mockedUser2 = mock(User); // create second mock
let user1 = instance(mockedUser1);
let user2 = instance(mockedUser2);
if(user1.id === user2.id)
  return true;
else
  return false;
```

Please reopen issue if something is still wrong.

**Comment by bjverhoe** [comment]
Hi @NagRock, thanks for the info!
