### ISSUE TITLE
How to mock fields

### ISSUE THREAD

**Issue by smstuebe** [NagRock/ts-mockito#23]
Is it currently possible to mock field values? Unfortunately, not everything is using `get` and `set` functions and exposing the field instead. 

    export class Foo {
        isBar: boolean;
    }    
    let fooMock = mock(Foo);
    when(fooMock.isBar).thenReturn(false);

throws the error:

>  TypeError: Cannot read property 'methodStubCollection' of undefined
            at MethodStubSetter.thenReturn (webpack:/~/ts-mockito/lib/MethodStubSetter.js:18:1)
            at Object.<anonymous> (webpack:/fooTests.ts:25:33)

Is there a cool way without using:

    let inst = instance(fooMock);
    inst.isBar = false;

?? 
If not, are you open for a pull request with an suggestion? 
If yes does it have to be similar to the java mockito way of doing it (if there is one)?

**Comment by NagRock** [comment]
Hi @smstuebe all pull requests are welcome!
I'm trying to be as close as possibile to Java version but if API could be even better its ok :)

**Comment by smstuebe** [comment]
So the answer to my initial question is: "No"?

**Comment by NagRock** [comment]
Yes "No" :) currently ts-mockito can't mock fields. If you like you can create PR with this feature or I will add it to my roadmap. Please give me feedback if you will try to implement this, so that we do not work on the same thing.

**Comment by Nateowami** [comment]
For anyone else coming here from Google:
The information in this issue is not up to date. It's now possible to mock properties. This is documented in the README: https://github.com/NagRock/ts-mockito

**Comment by laszlozahoranszky** [comment]
It does not seem to possible to mock fully a property.

For example, I want to mock an entity which has a property and method:
```ts
interface FooDbEntity {
  id: string;
  toJson(): string;
}
```

My product code would take such object read and set the id. 
All of my attempts failed to mock such object with ts-mockito.
With jest, it is pretty easy, but I'd rather use one mocking framework.

Please let me know if you knew an approach.
