### ISSUE TITLE
Missing lodash import in DeepEqualMatcher

### ISSUE THREAD

**Issue by Jnforja** [NagRock/ts-mockito#3]
DeepEqualMatcher is not importing lodash which causes a runtime error.

**Comment by NagRock** [comment]
Can you give me an example? Most of matchers uses lodash and it works for in my project without importing it.

**Comment by Jnforja** [comment]
This is the code from the file DeepEqualMatcher.ts
```javascript
import {Matcher} from './Matcher';

export function deepEqual(expectedValue:any):any {
    return new DeepEqualMatcher(expectedValue);
}

class DeepEqualMatcher extends Matcher {
    constructor(private expectedValue: any) {
        super();
    }

    match(value: any): boolean {
        return _.isEqual(this.expectedValue, value);
    }

    toString():string {
        return 'deepEqual(' + this.expectedValue + ')';
    }
}
```

Notice that the variable _ , in the method match, is not being defined as a lodash import.
Next time i'll do a pull request :)

**Comment by NagRock** [comment]
Should be fixed after @michalstocki PR https://github.com/NagRock/ts-mockito/pull/5

Please close issue if it works correctly now.
