### ISSUE TITLE
Resetting particular stub

### ISSUE THREAD

**Issue by waterplea** [NagRock/ts-mockito#34]
This is more of a question than an issue. I just started using ts-mockito and I am wondering if it is possible to "re-stub" a method to return different value? I am stubbing my method in beforeEach with a value that works for all tests but there is one particular test where I want it to return a different value. I know I can reset the mock, but that would remove ALL of the stubs, while I just want to change one. Is it possible?

**Comment by waterplea** [comment]
Looks like writing a new when() works, I guess it was my code that invalidated it when I tried it at first.

**Comment by NagRock** [comment]
Thanks for info. I Hope You like ts-mockito :)
