### ISSUE TITLE
Mock of restify response is not working

### ISSUE THREAD

**Issue by apiel** [NagRock/ts-mockito#44]
When I try to create a mock of the Restify Response,

```
import { mock } from 'ts-mockito';
import { Response } from 'restify';

const response: Response = mock(Response);
```
I get the error:

> Type 'Response' is not assignable to type 'Response'. Two different types with this name exist, but they are unrelated.
>   Property 'header' is missing in type 'Response'.

Is there any way to solve this issue?

thx

**Comment by NagRock** [comment]
Hello @apiel thanks for reporting this issue. Will take a look at this soon.

**Comment by NagRock** [comment]
I'm getting different error `ReferenceError: Response is not defined` and this is thrown because `Response` is an interface not class. `ts-mockito` currently can't mock interfaces. This feature will be added later.

**Comment by apiel** [comment]
Ok, thank you, looking forward ;-)
Do you know any mocking library for TS supporting interface?

**Comment by NagRock** [comment]
TypeMoq supports interface mocking.

**Comment by apiel** [comment]
I got exactly the same error with TypeMoq :-/ at the end, I manually created my mock. Hopefully soon it will work with your library. Thx again
