### ISSUE TITLE
Passing parameters to the constructor of a mocked class

### ISSUE THREAD

**Issue by saitho** [NagRock/ts-mockito#46]
Hi,

I want to mock a class that uses parameters in the constructor.
That class is a JS class (no TypeScript involved) and I need to pass a value to the constructor in order to create an instance of the class.

That is basically my test so far:
```
// import ts-mockito
import {mock, when, instance} from 'ts-mockito';

// needed for signature
import { TradeOffer } from 'steam-tradeoffer-manager';

// needed to get ts-mockito's clazz working
const TradeOffer = require("../../node_modules/steam-tradeoffer-manager/lib/classes/TradeOffer.js");

// original constructor is TradeOffer(manager, partner, token)
let mockedTradeOffer:TradeOffer = mock(TradeOffer);

// instantiation fails because the constructor checks if "partner" is valid
let offer = instance(mockedTradeOffer);
```

Do you have any ideas on how I can tackle that problem? Or do we need a new feature here? ^^

**Comment by NagRock** [comment]
Hi, sorry but I dont understand for what You need to pass any value to constructor. While You mocking class constructor is not called. So constuctor code wont be executed.

**Comment by saitho** [comment]
Not sure what happened there. I tried it again and it worked... ^^'
