### ISSUE TITLE
should not verify if missing arg

### ISSUE THREAD

**Issue by jamesdanged** [NagRock/ts-mockito#48]
Great framework! I noticed though that `verify` doesn't properly seem to check for different number of arguments/missing arguments.

    class Foo {
      bar(a?: number, b?: number) {}
    }
    let mockFoo = mock(Foo)
    let foo = instance(mockFoo)
    foo.bar(5)
    verify(mockFoo.bar(5, 6)).called()

This should throw a verification error but doesn't.

**Comment by NagRock** [comment]
Hi! Thanks for motivating words and reporting issue. Can you give me version number you are using?

**Comment by jamesdanged** [comment]
I'm on 2.2.1.

**Comment by NagRock** [comment]
Oh! This is very important issue, thanks for reporting this. I will fix this asap.

**Comment by NagRock** [comment]
@jamesdanged hi again, this issue should be fixed in version 2.2.2 https://github.com/NagRock/ts-mockito/releases/tag/v2.2.2

Please reopen this issue if something still works wrong.
Once again thanks for reporting this!

**Comment by jamesdanged** [comment]
Works great now. Thanks!
