### ISSUE TITLE
Stubbing fields and returning string

### ISSUE THREAD

**Issue by lucax88x** [NagRock/ts-mockito#49]
first of all, great library! simple and powerful.

I just want to mock a class and return a string on a precise field, but I'm getting an error on a precise case.

I'm wondering if it's a bug or I'm doing it wrongly?

WORKING Sample code

```typescript
export class DtoData {
    data: string;
}

const mockData = mock(DtoData );
when(mockData.data).thenReturn('test');
```

BREAKING Sample code because of the imGonnaBreakTheDto() method declared (but not used) in the class

```typescript
export class DtoData {
    data: string;

    imGonnaBreakTheDto() {
        return this.data && this.data;
    }
}

const mockData = mock(DtoData );
when(mockData.data).thenReturn('test');
```

this gives me 'Cannot read property 'add' of undefined' on the when because it finds 'data' as function instead of MethodToStub type when using the thenReturn.

Funny thing is that if I use only 

```typescript
imGonnaBreakTheDto() {
   return this.data;
}
```

it works.

**Comment by NagRock** [comment]
Hi @lucax88x thanks for for the kind words and reporting issue. I will try to reproduce this and fix asap.

**Comment by Markus-Ende** [comment]
Maybe the `return this.data && this.data` somehow adds property descriptors to the transpiled class code and interferes with the Proxy implementation?

**Comment by NagRock** [comment]
@lucax88x which version are you using? I can't reproduce this issue. Maybe you can provide example on github repository?

**Comment by lucax88x** [comment]
Sure, will do tomorrow!

**Comment by lucax88x** [comment]
you can grab the code here.

https://github.com/lucax88x/ts-test-runner/tree/ts-mockito-49

Just a thing I noticed, running tests with karma is fine, but with wallabyjs it gives the error mentioned above.

You wanna investigate why or I should ask wallabyjs guys?

**Comment by NagRock** [comment]
I will take a look at this and let you know.

**Comment by NagRock** [comment]
Thanks for sample code :)

**Comment by lucax88x** [comment]
you are welcome!

to be honest.. now I remember that I had the same issue also using karma (on the original project).

Maybe it's because we were using chrome as launcher? and chrome has a different implementation of Proxy than Electron I'm using on the sample?

**Comment by NagRock** [comment]
Sorry @lucax88x but I've run this on electron and chrome and both working fine. If you have still problem please provide some more examples.
