### ISSUE TITLE
Doc for Basic looks to be incorrect.

### ISSUE THREAD

**Issue by mconner** [NagRock/ts-mockito#59]
The Basic example in the README shows:
`let mockedFoo:Foo = mock(Foo);`

but the the verify has: 
`verify(fooMock.getBar(3)).called();`

fooMock is not defined.

**Comment by NagRock** [comment]
It should be `verify(mockedFoo.getBar(3)).called();`

Thanks for reporting. I will fix this soon.

**Comment by viman** [comment]
@mconner Thank you for reporting this.
@NagRock Fixed in #60.

**Comment by NagRock** [comment]
Thanks @viman
