### ISSUE TITLE
Module can't be bundled using rollup ("A module cannot import itself")

### ISSUE THREAD

**Issue by jjordan-dff** [NagRock/ts-mockito#65]
```
import * as mockito from "./ts-mockito";
export default mockito;
```

The ts-mockito module requires itself to export itself as default. I find this rather confusing, and it causes an error when bundling the module using rollup with rollup-plugin-commonjs ("A module cannot import itself
"). Isn't there are a cleaner solution to provide a default export?

**Comment by NagRock** [comment]
Default export has been added in https://github.com/NagRock/ts-mockito/pull/58 because `ember-browserify` can't handle named exports. 
 
I need to take a look deeper to reconcile both problems. Or maybe you got some suggestions?

**Comment by jjordan-dff** [comment]
https://github.com/NagRock/ts-mockito/pull/69

**Comment by NagRock** [comment]
Published in https://github.com/NagRock/ts-mockito/releases/tag/v2.2.10
Thanks @jjordan-dff for reporting and fixing this. Also sorry for long reaction time.
