### ISSUE TITLE
Why we need "instance()"?

### ISSUE THREAD

**Issue by ilbonte** [NagRock/ts-mockito#87]
Hi, I'm trying to understand why we need a separate function (`instance()`) to get an instance of a mocked class, since in the original (Java) version of mockito, `mock()` returns an instantiated object.

There is some technical limitation in Typesctipt?

**Comment by NagRock** [comment]
Hi @ilbonte yes this is technical limitation. I can't find any way to get rid of `instance` function.

**Comment by joshden** [comment]
Thanks, @NagRock. Coming from Mockito, I was confused on this as well when first looking at the Readme. Might be good to add to the Readme that this is a technical limitation.

**Comment by killdash9** [comment]
It was confusing to me as well -- A mention in the documentation would be nice.

**Comment by NagRock** [comment]
@killdash9 you're right. Currently I'm trying to get some solution to avoid using `instance` but this causes same problems as in Java mockito. Where using `when()` function causes real instance function call and forces using `doReturn('something').when...`.
