### ISSUE TITLE
Logic in public getters is actually executed when instantiating the mock

### ISSUE THREAD

**Issue by jamesmaila** [NagRock/ts-mockito#9]
If you have a class as follows

```
export class TestClass {
    constructor(private dependency: Dependency) { }
    public get myProperty(): string {
        return this.dependency.getVal();
    }
}
```

when running 
`let myMock = mock(TestClass);`

this.dependency.getVal() will actually get executed, and fail since this.dependency will be undefined.
Occurs when generating method stubs

**Comment by NagRock** [comment]
Thanks for Your report. i will take a look a this asap.

**Comment by NagRock** [comment]
Fixed in https://github.com/NagRock/ts-mockito/releases/tag/v1.1.3

Keep in mind, that it only fixes getter/setter code execution. Functionality of stubbing getter/setter will be added in future release.

**Comment by NagRock** [comment]
Please let me know if release 1.1.3 fixed yours issue.
