### ISSUE TITLE
mock<T> declared return type of T, but returnns not an instance of T

### ISSUE THREAD

**Issue by LokiMidgard** [NagRock/ts-mockito#90]
I started just started using this library. And had some problems getting starting, because I havent seen that ```instance(...)``` is needed.

I would expect that ```mock(...)``` would return some Generic type ```Mock<T>``` that will be used by the ```instance(...)``` method.

Then the compiler would throw an error.

**Comment by NagRock** [comment]
You're right. We got to do something to throw an error when somebody use mock as real instance. It's really annoying but type script has some limitations. Thanks for reporting this, users opinion is very important.

**Comment by NagRock** [comment]
Unfortunately current implementation does not allow to throw any error if some one using mock as instance :/ I'll try to think about some core changes that will allow this.
