### ISSUE TITLE
Mocker is undefined

### ISSUE THREAD

**Issue by ryuuji3** [NagRock/ts-mockito#91]
I'm trying to unit test a token service, but I get the error:
```
TypeError: Cannot read property 'getAllMatchingActions' of undefined
    at MethodStubVerificator.times (/Users/ryuuji3/Projects/Node/restaurant-manager/restaurant-manager-server/node_modules/ts-mockito/src/MethodStubVerificator.ts:32:63)
    at MethodStubVerificator.once (/Users/ryuuji3/Projects/Node/restaurant-manager/restaurant-manager-server/node_modules/ts-mockito/src/MethodStubVerificator.ts:20:14)
    at Object.<anonymous> (/Users/ryuuji3/Projects/Node/restaurant-manager/restaurant-manager-server/src/services/token.spec.ts:46:11)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/ryuuji3/Projects/Node/restaurant-manager/restaurant-manager-server/src/services/token.spec.ts:4:58)
    at <anonymous>
```
Here is my test: 
```ts
  describe('issue()', () => {
    let mockRepository : TokenRepository, repository : TokenRepository
    let user : User
    let jwt : string
    let token: Token
    let service : TokenService

    before(async () => {
      mockRepository = mock(TokenRepository)
      user = mockUser('example')

      let payload : PayloadI = Token.createPayload(user)
      jwt = await Token.sign(payload)
      token = await Token.create(user, jwt)

      when(mockRepository.register(user, jwt)).thenResolve(token)

      repository = instance(mockRepository)
      service = new TokenService(repository)
    })

    it('should call repository.register()', async () => {
      await service.issue(user)
        verify(
          repository.register(user, jwt)
        ).once()
    })
  })
```

Any idea of what's going wrong?

EDIT:
It appears I should have read the documentation better.
In order to check for behaviour, rather than return, you must verify the mocker method not the instance method.

Sorry!

**Comment by NagRock** [comment]
Verify should be called on mock not on instance. Looks similar to #90 issue

**Comment by ryuuji3** [comment]
Thank you, just noticed that when I re-read the documentation. Sorry about that!

**Comment by NagRock** [comment]
No problem, this just shows that we got not too good API and got to do something with that.

**Comment by ryuuji3** [comment]
Or if it's common enough of an issue, perhaps a helpful "Did you mean to call the mocker method instead?" would help. It makes much more sense now that I know, I don't think it's that bad.

**Comment by NagRock** [comment]
Ohh! Sometimes the simplest ideas are the best. I'll try to add this as "work around" for now if it will be possible. Thanks!

**Comment by ryuuji3** [comment]
No, thank you for your hard work! Maybe even easier would just be to add a note on the README, then no code changes need to be made. The error message makes sense already, just didn't realize it at the time.
