### ISSUE TITLE
Trouble verifying objects getting passed into function call

### ISSUE THREAD

**Issue by designxtek** [NagRock/ts-mockito#93]
It seems like I can't verify objects getting passed in.

```
// Using instance in source code
foo.getBar({ foo: "bar" });
 
// Explicit, readable verification
verify(mockedFoo.getBar({ foo: "bar" })).called();
```

Will fail

**Comment by NagRock** [comment]
By default `strictEqual` verifier is used. If you want to check objects values try using `deepEqual` verifier.
`verify(mockedFoo.getBar(deepEqual({ foo: "bar" }))).called();`

**Comment by designxtek** [comment]
ah thank you! Will try that.

**Comment by NagRock** [comment]
No problem. Please close issue if this solved your problem. Cheers

**Comment by designxtek** [comment]
That works! Thanks
